# Generated by Django 5.1.7 on 2025-04-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('host_name', models.CharField(blank=True, default='Anonymous', max_length=255)),
                ('host_room_url', models.URLField(max_length=2047)),
                ('viewer_room_url', models.URLField(max_length=2047)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('status', models.CharField(default='active', max_length=20)),
            ],
        ),
    ]
