# Generated by Django 5.1.7 on 2025-04-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionroom',
            name='increment',
            field=models.FloatField(default=1.0),
        ),
    ]
